<a href="https://colab.research.google.com/github/danghoangminh/CS336.L12.KHCL/blob/master/boolean_retrieval_term_document.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import glob
import numpy as np

In [3]:
files = glob.glob('/content/drive/My Drive/Colab Notebooks/boolean retrieval term-document/data/*.txt')
docs = []
for file in files:
    f = open(file, "r", encoding='utf-8')
    file_content = f.read()
    docs.append(file_content)

In [4]:
unique_terms = {term for doc in docs for term in doc.replace('.', ' ').replace('"', ' ').replace(',', ' ').split()}
term_doc_matrix = {}
for term in unique_terms:
  term_doc_matrix[term] = []
  for doc in docs:
    if term in doc:
      term_doc_matrix[term].append(1)
    else: 
      term_doc_matrix[term].append(0)

In [9]:
def check_term_exit(word):
  if word in term_doc_matrix:
    return np.array(term_doc_matrix[word])
  else:
    return np.zeros(len(docs_array), dtype=int)

In [12]:
with open('/content/drive/My Drive/Colab Notebooks/boolean retrieval term-document/query_list.txt', 'r', encoding='utf-8') as file:
  lst_query = file.read().splitlines()
  for line in lst_query:
    query = line.replace('"', ' ').split()
    docs_array = np.array(docs, dtype='object')
    if len(query) == 1:
      ans = np.array(term_doc_matrix[query[0]])
    elif len(query) > 2:
      ans = np.zeros(len(docs_array), dtype=int)
      for i in range(1, len(query)):
        if query[i] == "AND":
          word1 = query[i - 1]
          word2 = query[i + 1]
          arr1 = check_term_exit(word1)
          arr2 = check_term_exit(word2)
          ans = (arr1 & arr2)
        elif query[i] == "OR":
          word1 = query[i - 1]
          word2 = query[i + 1]
          arr1 = check_term_exit(word1)
          arr2 = check_term_exit(word2)
          ans = (arr1 | arr2)
        elif query[i] == "NOT":
          word1 = query[i - 1]
          word2 = query[i + 1]
          arr1 = check_term_exit(word1)
          arr2 = check_term_exit(word2)
          ans = (arr1 - arr2)
    print('\nVăn bản thỏa truy vấn: ', line)
    print(ans)


Văn bản thỏa truy vấn:  "Ronaldo" AND "Brazil"
[0 0 1 1 0 0 0 0 0 0]

Văn bản thỏa truy vấn:  "Messi" AND "Suarez"
[0 0 0 0 0 0 0 0 0 0]

Văn bản thỏa truy vấn:  "Trump" AND "Covid"
[0 0 0 0 0 0 0 0 0 0]

Văn bản thỏa truy vấn:  "Trump" AND "Biden"
[0 0 0 0 0 0 1 1 0 0]

Văn bản thỏa truy vấn:  "Trump" AND "Biden" NOT "Covid"
[0 0 0 0 0 0 1 1 0 0]

Văn bản thỏa truy vấn:  "SARS-CoV-2"
[0 0 0 0 0 1 1 0 0 0]
